pipeline {
  agent any
    
  environment {	
    IMAGE_TAG = "${BUILD_NUMBER}"
    DOCKER_CREDENTIALS_ID = "docker_id"
    GITHUB_CREDENTIALS_ID = "git_pat_id"
}
  stages {
  
    stage('Checkout') {
      steps {
        git url: 'https://github.com/bimal-root/cicd-end-to-end.git',
	  branch: 'main',
	  credentialsId: 'git_pat_id'
          }
}

    stage('Move Subfolder and List files') {
      steps {
	dir('Project_2'){
        script {
	  sh '''  
	  pwd && ls -la
	  '''
}
}	
}
}
    stage('Build Docker Image') {
      steps {
        script {
	  sh '''
	  docker build -t bimalrajsharma07/myimage:${BUILD_NUMBER} .
	  '''
}
}
}
    stage('Docker Login and Push') {
      steps {
        script {
	  withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
	    sh '''
	    echo "Login to Docker Hub.."
	    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
	    echo "Pushing image to docker hub"
	    docker push bimalrajsharma07/myimage:${BUILD_NUMBER}
	    '''
}
}
}	
}
    stage('Checkout K8S Manifest') {
      steps {
        git url: "https://github.com/bimal-root/cicd-end-to-end.git"
	branch: 'main'
	credentialsId: 'git_pat_id'
	
	dir('Project_2/k8s_Deploy'){
	  sh 'ls -la'
}
}
}


}
}

